### ISSUE TITLE
OIDC not working

### ISSUE THREAD

**Issue by ilbarone87** [autobrr/dashbrr#70]
**Describe the bug**
After adding the env vars for OIDC, I'm getting this error trying to log in `{"code":5, "message":"Not Found"}`.
I currently use Zitadel as identity portal. Dashbrr runs on kubernetes 1.31 (OS sublayer is Ubuntu 24.04). I have succesfully set up other apps with OIDC that runs in k8s (such as portainer, oauth2-proxy or grafana)
These are the envs:

```
- name: OIDC_ISSUER
   value: "https://zitadel.mydomain.net"
- name: OIDC_CLIENT_ID
  valueFrom:
      secretKeyRef:
          name: media-secret
          key: OIDC_CLIENT_ID
- name: OIDC_CLIENT_SECRET
   valueFrom:
       secretKeyRef:
           name: media-secret
            key: OIDC_CLIENT_SECRET
 - name: OIDC_REDIRECT_URL
    value: "https://dashbrr.mydomain.net/api/auth/callback"
```
Double checked in the actual container and the CLIENT_ID and CLIENT_SECRET are loaded correctly.
ZItadel is configured correctly to redirect to this URL https://dashbrr.mydomain.net/api/auth/callback

![Image](https://github.com/user-attachments/assets/7d0df51a-69b2-4e84-9927-26a67a7eb74d)

Logs in container aren't showing anything apart from "authentication flow intiated". Looking at the network log in chrome I can see this:

`https://zitadel.mydoamin.net/authorize?client_id=redacted&nonce=redacted&redirect_uri=https%3A%2F%2Fdashbrr.mydomain.net%2Fapi%2Fauth%2Fcallback&response_type=code&scope=openid+profile+email&state=redacted`

```
:authority:
zitadel.mydomain.net
:method:
GET
:path:
/authorize?client_id=redacted&nonce=redacted&redirect_uri=https%3A%2F%2Fdashbrr.mtdomain.net%2Fapi%2Fauth%2Fcallback&response_type=code&scope=openid+profile+email&state=redacted
:scheme:
https
accept:
text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
accept-encoding:
gzip, deflate, br, zstd
accept-language:
it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7
cookie:
mode=auto-dark; __Host-zitadel.login.csrf=redacted_cookie
priority:
u=0, i
referer:
https://dashbrr.mydomain.net/
```

This happens on both an existent or fresh newly installed instance.
